---
title: "Figure 2 code"
author: "Ngoc Nguyen"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(MASS) 
library(reshape2) 
library(ggrepel)
library(reshape)
library(reshape2)
library(tidyverse)
library(dbplyr)
library(dplyr)
library(foreach)
library(doParallel)
library(purrr)
library(broom)
library(scales)
library(gghalves)
# Load libraries
library(ggplot2)
library(rnaturalearth)
library(sf)
library(terra)    
library(tidyr)      
library(patchwork)

#Function to scale variables to 0-1 range
scale_01 <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}

#Function to calculate the correlation of detrended x and y variables
detrend_linear <- function(a1, a2) {
  length_array <- length(a1)
  index <- 1:length_array
  
  df_lm <- data.frame(a1, a2, index)
  df_lm <- na.omit(df_lm)
  
  lm_a1 <- lm(a1 ~ index, df_lm)
  lm_a2 <- lm(a2 ~ index, df_lm)

  a1_fit <- predict(lm_a1)
  a2_fit <- predict(lm_a2)
  a1_detrend <- a1 - a1_fit
  a2_detrend <- a2 - a2_fit

  cor_df <- cor.test(a1_detrend, a2_detrend, method = "pearson")    
  r_detrend <- cor_df$estimate
  p_detrend <- cor_df$p.value
  
  p_linear_a1 <- summary(lm_a1)$coefficients[2,4]
  p_linear_a2 <- summary(lm_a2)$coefficients[2,4]
    
  return(c(r_detrend, p_detrend, p_linear_a1, p_linear_a2))
}

#Function to calculate the correlation of x and y variables
linear <- function(df) {
  cor_df <- cor.test(df$gpp, df$cWood, method = "pearson")    
  r <- cor_df$estimate
  p <- cor_df$p.value
    
  return(c(r, p))
}

response_ratio <- function(df) {
  lm_a1 <- lm(gpp ~ year, df)
  lm_a2 <- lm(cWood ~ year, df)
  a1_fit <- predict(lm_a1)
  a2_fit <- predict(lm_a2)
  length_array <- length(a1_fit)
  ratio = log(a1_fit[length_array]/a1_fit[1])/log(a2_fit[length_array]/a2_fit[1])
  return(ratio)
}
```

#Plot the scatter plot of correlation for all models in S1
```{r}
model_name_list = c("ISBA-CTRIP", "CLM5.0", "ORCHIDEE", "ORCHIDEEv3", "CLASSIC-N", "CLASSIC", "CABLE-POP", "LPX-Bern")
var_name = "cWood"

df_list <- list()
for(i in model_name_list) {
#Fluxes
gpp_df_S1 <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", i, "/gpp_S1_31_site_weighted_yearly_mean.csv", sep = ""))
df_var_sub <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", i, "/", var_name, "_S1_31_site_weighted_yearly_mean.csv", sep = ""))

year_chosen = 1950

if(model_name == "CLM5.0") {
  gpp_df_sub_S1 <- subset(gpp_df_S1, !is.na(gpp) & year > year_chosen & year < 2020 & gpp != 0)
  df_var_sub <- subset(df_var_sub, !is.na(cWood) & cWood != 0 & year > year_chosen)
} else {
  gpp_df_sub_S1 <- subset(gpp_df_S1, !is.na(gpp) & year > year_chosen & year < 2020 & gpp != 0)
  df_var_sub <- subset(df_var_sub, !is.na(cWood) & cWood != 0 & year > year_chosen)
}


cWood_df_sub_S1 <- inner_join(gpp_df_sub_S1, df_var_sub, by = c("year", "lat", "lon"))
 
cWood_df_increment_S1 <- cWood_df_sub_S1 %>%
  arrange(lat, lon, year) %>%
  group_by(lat, lon) %>%
  mutate(
    biomass_increment = .data[[var_name]] - lag(.data[[var_name]]),
  ) %>%
  ungroup()

try_detrend <- function(x, y, idx) {
  if(sum(is.finite(x) & is.finite(y)) >= 40) detrend_linear(x, y)[idx] else NA_real_
}


beta_df <- cWood_df_increment_S1 %>%
  filter(!is.na(biomass_increment), !is.na(gpp)) %>%
  group_by(lat, lon) %>%
  summarise(
    r_detrend_delta = try_detrend(biomass_increment, gpp, 1),
    beta = response_ratio(cur_data())
  )

unique_df <- beta_df[!duplicated(beta_df[c("lat", "lon", "beta", "r_detrend_delta")]), ]
unique_df <- na.omit(unique_df)
unique_df$model <- i

df_list[[i]] <- unique_df[, c("lat", "lon", "model", "beta", "r_detrend_delta")]

}

merged_beta_df <- do.call(rbind, df_list)

summary(lm(r_detrend_delta~beta, subset(merged_beta_df, beta > -5 & beta < 10)))

summary_df <- subset(merged_beta_df, beta > -5 & beta < 10) %>%
  group_by(model) %>%
  summarise(
    yQ1 = quantile(beta, 0.25),
    yQ2 = quantile(beta, 0.5),
    yQ3 = quantile(beta, 0.75),
    xQ1 = quantile(r_detrend_delta, 0.25),
    xQ2 = quantile(r_detrend_delta, 0.5),
    xQ3 = quantile(r_detrend_delta, 0.75)
  )

```


```{r}
# Plot + whiskers
p_local <- ggplot(summary_df, aes(x = xQ2, y = yQ2)) +
  geom_segment(aes(x = xQ1, xend = xQ3, y = yQ2, yend = yQ2), size = 0.4, color = "gray50") + 
  geom_segment(aes(x = xQ1, xend = xQ1, y = yQ2 - 0.03, yend = yQ2 + 0.03), size = 0.4, color = "gray50") +
  geom_segment(aes(x = xQ3, xend = xQ3, y = yQ2 - 0.03, yend = yQ2 + 0.03), size = 0.4, color = "gray50") +

  geom_segment(aes(x = xQ2, xend = xQ2, y = yQ1, yend = yQ3), size = 0.4, color = "gray50", lineend = "square") +  
  geom_segment(aes(x = xQ2 - 0.015, xend = xQ2 + 0.015, y = yQ1, yend = yQ1), size = 0.4, color = "gray50") +
  geom_segment(aes(x = xQ2 - 0.015, xend = xQ2 + 0.015, y = yQ3, yend = yQ3), size = 0.4, color = "gray50") +
  
  geom_point(size = 2, shape = 21, fill = "#00a087", color = "#00a087", alpha = 0.8) + 
  
  geom_text_repel(
    aes(label = model), color = "#00a087",
    box.padding = 1,
    point.padding = 1,
    segment.color = NA,
    nudge_x = 0.13,
    nudge_y = 0.12,
    force = 10, size = 3.5
  ) +     
   theme_bw() + theme(
  legend.key.size = unit(1, 'cm'),
          axis.text.y = element_text(size = 12),
          axis.text.x = element_text(size = 12),
          axis.title.y = element_text(size = 12),
          axis.title.x = element_text(size = 12),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()) +
  labs(x = expression(r[italic(ΔcWood)~","~italic(GPP)]), y = expression(β[italic(cWood)~","~italic(GPP)])) + xlim(0,1)  + annotate("text",
           x = -Inf,      
           y = Inf,      
           label = expression("n = 201, P = 0.35, slope = -0.02"),
           hjust = -0.65,  
           vjust =  1.8,  
           size = 4)


save_path = paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/figures/beta_r_site_log_1950-Present-fix-31-not-scale-CLM-filter.png")

png(save_path,  width     =4.5,
    height    = 4.5,
    units     = "in",
    res       = 1200,
    pointsize = 4)

print(p_local)

dev.off()

```





