---
title: "Figure 3 code"
author: "Ngoc Nguyen"
date: "2025-12-05"
output: html_document
---

```{r}

# List of required libraries
required_libraries <- c(
  "ggplot2", "MASS", "reshape2", "ggrepel", "reshape", "tidyverse", 
  "dbplyr", "dplyr", "foreach", "doParallel", "purrr", "broom", 
  "scales", "rnaturalearth", "sf", "terra", "purrr", "tidyr")    

# Install missing libraries
for (lib in required_libraries) {
  if (!require(lib, character.only = TRUE)) {
    install.packages(lib, dependencies = TRUE)
  }
}

# Load all libraries
lapply(required_libraries, library, character.only = TRUE)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(MASS) 
library(reshape2) 
library(ggrepel)
library(reshape)
library(reshape2)
library(tidyverse)
library(dbplyr)
library(dplyr)
library(foreach)
library(doParallel)
library(purrr)
library(broom)
library(scales)

# Load libraries
library(ggplot2)
library(rnaturalearth)
library(sf)
library(terra)    
library(tidyr)      

library(ggbreak)
library(greekLetters)
generate_sequence <- function(n) {
  alphabet <- unlist(strsplit("ABCDEFGHIJKLMNOPQRSTUVWXYZ", split = ""))
  return(alphabet[1:n])
}
scale_01 <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}

response_ratio <- function(a1, a2) {
  length_array <- length(a1)
  index <- 1:length_array
  df_lm <- data.frame(a1, a2, index)
  df_lm <- na.omit(df_lm)
  lm_a1 <- lm(a1 ~ index, df_lm)
  lm_a2 <- lm(a2 ~ index, df_lm)
  if(summary(lm_a1)$coefficients[2,4] < 0.05 & summary(lm_a2)$coefficients[2,4] < 0.05) {
    a1_fit <- predict(lm_a1)
    a2_fit <- predict(lm_a2)
    ratio = ((a1_fit[length_array] - a1_fit[1])/a1_fit[1])/((a2_fit[length_array] - a2_fit[1])/a2_fit[1])
  } else {
    ratio = 0
  }
  return(ratio)
}



response_ratio_multiple <- function(df, window) {
  tryCatch({
  year_list <- df$year[1] : df$year[length(df$year)]
  no_win <- length(year_list) %/% window
  remain <- length(year_list) %% window
  
  ratio_list <- c()
  yr_start <- c()
  yr_end <- c()

  for(i in 1:no_win) {
    year_start <- year_list[(1 + (i-1)*window)]
    year_end <- year_list[i*window]
    df_sub <- subset(df, year >= year_start & year <= year_end)
    
    a1_sub <- df_sub$scale_biomass
    a2_sub <- df_sub$scale_gpp
    
    ratio <- response_ratio(a1_sub, a2_sub)
    ratio_list <- append(ratio_list, ratio)
    yr_start <- append(yr_start, year_start)
    yr_end <- append(yr_end, year_end)
  }
  
  if (remain > 9) {
    year_start <- year_list[(1 + no_win*window)]
    year_end <- year_list[(no_win*window + remain)]
    df_sub <- subset(df, year >= year_start & year <= year_end)
    
    a1_sub <- df_sub$scale_biomass
    a2_sub <- df_sub$scale_gpp
    
    ratio <- response_ratio(a1_sub, a2_sub)
    ratio_list <- append(ratio_list, ratio)
    yr_start <- append(yr_start, year_start)
    yr_end <- append(yr_end, year_end)
}
  
  df_final <- data.frame(yr_start, yr_end, ratio_list)
  return(df_final)
  }, error = function(err) { })
}

response_ratio_moving_window <- function(df, window) {
  tryCatch({
    
  year_list <- df$year[1] : df$year[length(df$year)]
  
  ratio_list <- c()
  yr_start <- c()

  for(i in 1:(length(year_list) - window)) {
    year_start <- year_list[i]
    year_end <- year_list[i] + window
    df_sub <- subset(df, year >= year_start & year <= year_end)
    
    a1_sub <- df_sub$scale_biomass
    a2_sub <- df_sub$scale_gpp
    
    ratio <- response_ratio(a1_sub, a2_sub)
    ratio_list <- append(ratio_list, ratio)
    yr_start <- append(yr_start, year_start)
  }
  
  df_final <- data.frame(yr_start, ratio_list)
  return(df_final)
  
  }, error = function(err) { })
}

percent_increase <- function(a1) {
  length_array <- length(a1)
  index <- 1:length_array
  df_lm <- data.frame(a1, index)
  df_lm <- na.omit(df_lm)
  tryCatch ({
    lm_a1 <- lm(a1 ~ index, df_lm)
    a1_fit <- predict(lm_a1)
    percent_incr = ((a1_fit[length_array] - a1_fit[1])/a1_fit[1])*100
    
    if(summary(lm_a1)$coefficients[2,4] < 0.05) {
        return(c(percent_incr, 1))
     } else {
        return(c(percent_incr, 0))
     }
    
    }, error = function(err) { 
      return(c(0, 0))
  }) 
}

```


#examining C allocation to other C fluxes/pools
```{r}
model_name_list <- c("CLASSIC", "CLASSIC-N", "CABLE-POP", "CLM5.0", "ISBA-CTRIP",  "ORCHIDEE", "ORCHIDEEv3", "LPX-Bern")
scenario = "S1"
for(i in 1:length(model_name_list)) {
  model_name = model_name_list[[i]]
  
  #Fluxes
  ra_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/ra_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  gpp_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/gpp_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cWood_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cWood_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cLeaf_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cLeaf_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cRoot_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cRoot_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  #remove grid cells with zero or NA values for each variable

  if(model_name == "CLM5.0") {
    ra_df_sub <- subset(ra_df, !is.na(ra) & year > 1950 & year < 2020 & ra != 0)
    gpp_df_sub <- subset(gpp_df, !is.na(gpp) & year > 1950 & year < 2020 & gpp != 0)
    cWood_df_sub <- subset(cWood_df, !is.na(cWood) & year > 1950 & year < 2020 & cWood != 0)
    cLeaf_df_sub <- subset(cLeaf_df, !is.na(cLeaf) & year > 1950 & year < 2020 & cLeaf != 0)
    cRoot_df_sub <- subset(cRoot_df, !is.na(cRoot) & year > 1950 & year < 2020 & cRoot != 0)
  } else {
    ra_df_sub <- subset(ra_df, !is.na(ra) & year > 1950 & ra != 0)
    gpp_df_sub <- subset(gpp_df, !is.na(gpp) & year > 1950 & gpp != 0)
    cWood_df_sub <- subset(cWood_df, !is.na(cWood) & year > 1950 & cWood != 0)
    cLeaf_df_sub <- subset(cLeaf_df, !is.na(cLeaf) & year > 1950 & cLeaf != 0)
    cRoot_df_sub <- subset(cRoot_df, !is.na(cRoot) & year > 1950 & cRoot != 0)
  }
  
  cWood_df_increment <- cWood_df_sub %>%
        arrange(lat, lon, year) %>% 
        group_by(lat, lon) %>%
        mutate(
              cWood_increment = (.data[["cWood"]] - lag(.data[["cWood"]]) )/60/60/24/365,
              ) %>%
        ungroup()
  
  cLeaf_df_increment <- cLeaf_df_sub %>%
        arrange(lat, lon, year) %>% 
        group_by(lat, lon) %>%
        mutate(
              cLeaf_increment = (.data[["cLeaf"]] - lag(.data[["cLeaf"]]))/60/60/24/365,
              ) %>%
        ungroup()
  
  cRoot_df_increment <- cRoot_df_sub %>%
        arrange(lat, lon, year) %>% 
        group_by(lat, lon) %>%
        mutate(
              cRoot_increment = (.data[["cRoot"]] - lag(.data[["cRoot"]]))/60/60/24/365,
              ) %>%
        ungroup()
  
  merge_flux <- list(ra_df_sub, gpp_df_sub, cWood_df_increment, 
                     cLeaf_df_increment, cRoot_df_increment) %>% 
                    reduce(full_join, by = c("year", "lat", "lon"))
  
  merge_flux <- merge_flux %>%
    group_by(lat, lon) %>%
    summarise(
      across(
        .fns = ~ mean(.x, na.rm = TRUE) 
      ),
      .groups = "drop"
    )
  
  
  merge_flux_sub <- subset(merge_flux, !is.na(ra) & !is.na(gpp) & !is.na(cWood_increment) & !is.na(cLeaf_increment) & !is.na(cRoot_increment))
  
  merge_flux_sub$ra_gpp_ratio <- merge_flux_sub$ra/merge_flux_sub$gpp*100

  merge_flux_sub$cWood_gpp_ratio <- merge_flux_sub$cWood_increment/merge_flux_sub$gpp*100
  merge_flux_sub$cLeaf_gpp_ratio <- merge_flux_sub$cLeaf_increment/merge_flux_sub$gpp*100
  merge_flux_sub$cRoot_gpp_ratio <- merge_flux_sub$cRoot_increment/merge_flux_sub$gpp*100
  
  merge_flux_select <- merge_flux_sub[, c("lat", "lon", "ra_gpp_ratio", "cWood_gpp_ratio", "cLeaf_gpp_ratio", "cRoot_gpp_ratio")]
  
  colnames(merge_flux_select) <- c("lat", "lon", "ra",  "cWood", "cLeaf", "cRoot")
  merge_flux_select$model <- model_name
  
  
  path_save1 = paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/",  model_name, "_", scenario, "allocation_annual_TRENDYv10", ".csv", sep = "")
  write.csv(merge_flux_select, path_save1)
}


```

#Calculate the long-term increase of other C fluxes/pools
```{r}
model_name_list <- c("CLASSIC", "CLASSIC-N", "CABLE-POP", "CLM5.0", "ISBA-CTRIP",  "ORCHIDEE", "LPX-Bern", "ORCHIDEEv3")
scenario = "S1"

for(i in 1:length(model_name_list)) {
  model_name = model_name_list[[i]]
  
  #Fluxes
  ra_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/ra_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  gpp_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/gpp_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cWood_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cWood_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cLeaf_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cLeaf_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  cRoot_df <- read.csv(paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/TRENDYv10/31_site_weighted/", model_name, "/cRoot_", scenario, "_31_site_weighted_yearly_mean.csv", sep = ""))
  
if(model_name == "CLM5.0") {
  ra_df_sub <- subset(ra_df, !is.na(ra) & year > 1950 & year < 2020 & ra != 0)
  gpp_df_sub <- subset(gpp_df, !is.na(gpp) & year > 1950 & year < 2020 & gpp != 0)
  cWood_df_sub <- subset(cWood_df, !is.na(cWood) & year > 1950 & year < 2020 & cWood != 0)
  cLeaf_df_sub <- subset(cLeaf_df, !is.na(cLeaf) & year > 1950 & year < 2020 & cLeaf != 0)
  cRoot_df_sub <- subset(cRoot_df, !is.na(cRoot) & year > 1950 & year < 2020 & cRoot != 0)
} else {
  ra_df_sub <- subset(ra_df, !is.na(ra) & year > 1950 & ra != 0)
  gpp_df_sub <- subset(gpp_df, !is.na(gpp) & year > 1950 & gpp != 0)
  cWood_df_sub <- subset(cWood_df, !is.na(cWood) & year > 1950 & cWood != 0)
  cLeaf_df_sub <- subset(cLeaf_df, !is.na(cLeaf) & year > 1950 & cLeaf != 0)
  cRoot_df_sub <- subset(cRoot_df, !is.na(cRoot) & year > 1950 & cRoot != 0)
}
  
  gpp_df_percent <- gpp_df_sub %>%
    group_by(lat, lon) %>% 
    arrange(year) %>% 
    summarise(
      tmp = list(percent_increase(gpp)),
      gpp_percent = tmp[[1]][1], 
      p_gpp = tmp[[1]][2]
    ) %>% ungroup()
  
  ra_df_percent <- ra_df_sub %>%
    group_by(lat, lon) %>% 
    arrange(year) %>% 
    summarise(
      tmp = list(percent_increase(ra)),
      ra_percent = tmp[[1]][1], 
      p_ra = tmp[[1]][2]
    ) %>% ungroup()
  
  cLeaf_df_percent <- cLeaf_df_sub %>%
    group_by(lat, lon) %>% 
    arrange(year) %>% 
    summarise(
      tmp = list(percent_increase(cLeaf)),
      cLeaf_percent = tmp[[1]][1], 
      p_cLeaf = tmp[[1]][2]
    ) %>% ungroup()
  
  cWood_df_percent <- cWood_df_sub %>%
    group_by(lat, lon) %>% 
    arrange(year) %>% 
    summarise(
      tmp = list(percent_increase(cWood)),
      cWood_percent = tmp[[1]][1], 
      p_cWood = tmp[[1]][2]
    ) %>% ungroup()
  
  cRoot_df_percent <- cRoot_df_sub %>%
    group_by(lat, lon) %>% 
    arrange(year) %>% 
    summarise(
     tmp = list(percent_increase(cRoot)),
      cRoot_percent = tmp[[1]][1], 
      p_cRoot = tmp[[1]][2]
    ) %>% ungroup()
  
  
  merge_flux_percent <- list(gpp_df_percent, ra_df_percent, cWood_df_percent, 
                     cLeaf_df_percent, cRoot_df_percent) %>% 
                    reduce(full_join, by = c("lat", "lon"))
  
  
  merge_flux_select_percent <- merge_flux_percent[, c("lat", "lon", "gpp_percent", "ra_percent", "cWood_percent", "cLeaf_percent", "cRoot_percent", "p_gpp", "p_ra", "p_cWood", "p_cLeaf", "p_cRoot")]
  colnames(merge_flux_select_percent) <- c("lat", "lon", "gpp", "ra", "cWood", "cLeaf", "cRoot", "p_gpp", "p_ra", "p_cWood", "p_cLeaf", "p_cRoot")
  
  merge_flux_select_percent$model <- model_name

#   print(ggplot(melt(data.frame(merge_flux_select_percent_sub[, c("gpp", "ra", "cWood", "cLeaf", "cRoot", "model")])), aes(x = variable, y = value)) + 
#     geom_jitter(aes(color = model)) + 
#     geom_boxplot(outlier.shape = NA, alpha = 0.7)  + theme_bw() +
#     ylab("%increase from 1950-Present"))
  
  path_save2 = paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/",  model_name, "_", scenario, "_", "longterm-increase_TRENDYv10_sign_mark_31", ".csv", sep = "")
  
  write.csv(merge_flux_select_percent, path_save2)
  
}



```

#combine all the dataframe together for allocation mean across all models
```{r}
model_name_list <- c("CLASSIC", "CLASSIC-N", "CABLE-POP", "CLM5.0", "ISBA-CTRIP", "LPX-Bern", "ORCHIDEE", "ORCHIDEEv3")

df_list <- list()
for(i in 1:length(model_name_list)) {
  path_read = paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/",  model_name_list[i], "_S1allocation_annual_TRENDYv10.csv", sep = "")
  df <- read.csv(path_read)
  df_list[[i]] <- df
}


# Combine all the individual pulse data frames into a single data frame
combined_df_longterm <- NULL
for(k in 1:length(df_list)) {
  combined_df_longterm <- rbind(combined_df_longterm, df_list[[k]])
}          

colnames(combined_df_longterm) <- c("X", "lat", "lon", "ra", paste(greeks("Delta"), "cWood", sep = ""), 
                                        paste(greeks("Delta"), "cLeaf", sep = ""), 
                                        paste(greeks("Delta"), "cRoot", sep = ""), "model")

png("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/figures/annual_allocation_trendyv10_S1.png",  width     = 4.7,
    height    = 3,
    units     = "in",
    res       = 1200,
    pointsize = 4)
ggplot(melt(data.frame(combined_df_longterm[, 2:6])), aes(y = value, x = variable)) + 
  geom_jitter(size = 1, aes(color = model)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.7)  + theme_bw() +
  ylab("Annual %GPP allocated to ")  + scale_y_break(c(5, 25),
                space = 0.1,            # adjust gap size
                scales = c(1, 1),       # keep same scale in both segments
                cutline = TRUE,         # draw the cut line
                cutline_col = "black",  # color of the zig‑zag
                cutline_type = "zigzag",# style of the cut
                cutline_width = 0.7     # thickness of the cut
  ) 

dev.off()

write.csv(melt(data.frame(combined_df_longterm[, 4:8])), "/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/allocation_S1.csv")

```

#combine the long-term increase datasets
```{r}
model_name_list <- c("CLASSIC", "CLASSIC-N", "CABLE-POP", "CLM5.0", "ISBA-CTRIP", "LPX-Bern", "ORCHIDEE", "ORCHIDEEv3")
df_list <- list()
for(i in model_name_list) {
  path_read = paste("/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/",  i, "_", "S1_longterm-increase_TRENDYv10_sign_mark_31", ".csv", sep = "")
  df <- read.csv(path_read)
  df_list[[i]] <- df
}

# Combine all the individual pulse data frames into a single data frame
combined_df_longterm <- NULL
for(k in 1:length(df_list)) {
  combined_df_longterm <- rbind(combined_df_longterm, df_list[[k]])
}          
 
combined_df_longterm_sub <- subset(combined_df_longterm, p_gpp == 1 & p_ra == 1 & p_cWood == 1 & p_cRoot == 1 & p_cLeaf == 1)

write.csv(melt(na.omit(data.frame(combined_df_longterm[, c("gpp", "ra", "cWood", "cLeaf", "cRoot", "model")]))), "/Users/ngocnguyen/Library/CloudStorage/Box-Box/Projects/biomass_paper/results/datasets/longterm_S1_31.csv")
```




































